=== kkimmy/InfraJSON-1/schema/v01/infrajson.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "InfraJSON v0.1",
  "description": "InfraJSON specifications v0.1",
  "type": "object",

  "properties": {
    "type": { "enum": ["InfraJSON"] },
    "version": { 
      "type": "string",
      "pattern": "^(\\d\\.)(\\d+\\.)?(\\*|\\d+)$"
    },
    "metadata": {
      "type": "object",
      "properties":{
          "datasetID": {"type": "string"},
          "scope": {"type": "string"},
          "name": {"type": "string"},
          "description": {"type": "string"},
          "dateTime": {"type": "string",  "format":"date-time"},
          "datasetVersion": {"type": "string", "pattern":"\\d.\\d"},
          "application": {"type": "string"},
          "author": {"type": "string"},
          "infraVersion": {"type": "string", "pattern":"\\d.\\d" },
          "language": {"type": "string"},
          "defaultCRS" : {"type": "string", "pattern":"^urn:ogc:def:crs:EPSG::[0-9]{4,5}$"}
      } 
    },
    "features": {
      "type": "object",
      "additionalProperties": {
      "oneOf": [
          { "$ref": "infrajsonfeatures.json#/LandFeature" },
          { "$ref": "infrajsonfeatures.json#/Facility" },
          { "$ref": "infrajsonfeatures.json#/LandDivision" },
          { "$ref": "infrajsonfeatures.json#/Survey" },
          { "$ref": "infrajsonfeatures.json#/Document" },
          { "$ref": "infrajsonfeatures.json#/SurveyMark" },
          { "$ref": "infrajsonfeatures.json#/Set" }
      ]
      }
    },
    
    "vertices": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {"type": "number"},
        "minItems": 3,    
        "maxItems": 3
      }
    }
  },
  "required": ["type", "version", "features","vertices"],
  "additionalProperties": false
}

=== kkimmy/InfraJSON-1/sampledata/example_infrajson.json
{
  "type": "InfraJSON",
  "version": "0.1",
   "metadata": {
       "datasetID": "GML_e8e7963f-718c-40fb-8253-753f2d468f0f",
       "scope": "OGC LandInfraSWG",
       "name": "Land Infra Dataset",
       "description": "Land Infra Dataset of terrain",
       "dateTime": "2018-10-04T16:52:59",
       "datasetVersion": "1.0",
       "application": "Generated using CityGML2InfraGML python program",
       "author": "uKnowMe",
       "infraVersion": "0.1",
       "language": "English",
       "defaultCRS" : "urn:ogc:def:crs:EPSG::4326"
   },
   "features":{
        "ls1": {
            "type": "LandFeature"
        },
        "ls2": {
            "type": "LandFeature"
        }
   },
  "vertices": [
    [0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
    [1.0, 0.0, 1.0],
    [1.0, 1.0, 1.0],
    [11.0, 11.0, 11.0],
    [21.0, 21.0, 21.0],
    [31.0, 31.0, 31.0],
    [31.0, 41.0, 41.0],
    [31.0, 51.0, 51.0],
    [771.0, 61.0, 1.0],
    [0.0, 1.0, 1.0]
  ]
}
